/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.multichatproject;

import java.net.Socket;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali Haydar
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form ClientFrame
     */
    Client client;
    Socket socket;
    User user;

    DefaultListModel project_list = new DefaultListModel();

    public ClientFrame() {
        initComponents();

        lst_project.setModel(project_list);

        if (user != null) {
            for (int i = 0; i < user.projectList.size(); i++) {
                project_list.addElement(user.projectList.get(i).name + " -> " + user.projectList.get(i).projectKey);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_message = new javax.swing.JTextArea();
        btn_send = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_messages = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_project = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_joinChat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_projectName = new javax.swing.JTextField();
        btn_createProejct = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_projectKey = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txt_projectKeyJoin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_join = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username :");

        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        txt_message.setColumns(20);
        txt_message.setRows(5);
        txt_message.setEnabled(false);
        jScrollPane1.setViewportView(txt_message);

        btn_send.setText("SEND");
        btn_send.setEnabled(false);
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        lst_messages.setEnabled(false);
        jScrollPane2.setViewportView(lst_messages);

        lst_project.setEnabled(false);
        jScrollPane3.setViewportView(lst_project);

        jLabel2.setText("Project List");

        btn_joinChat.setText("JOIN THE CHAT");
        btn_joinChat.setEnabled(false);
        btn_joinChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinChatActionPerformed(evt);
            }
        });

        jLabel3.setText("Project Name: ");

        txt_projectName.setEnabled(false);

        btn_createProejct.setText("CREATE");
        btn_createProejct.setEnabled(false);
        btn_createProejct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createProejctActionPerformed(evt);
            }
        });

        jLabel4.setText("Project Key : ");

        jLabel5.setText("Password");

        jLabel6.setText("JOIN THE PROJECT");

        jLabel7.setText("Project Key :");

        btn_join.setText("JOIN");
        btn_join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_joinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_joinChat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_send, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_projectKeyJoin)
                                    .addComponent(btn_join, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_createProejct, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(txt_projectName)
                                    .addComponent(lbl_projectKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login)
                    .addComponent(jLabel5)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(btn_send)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_projectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(btn_createProejct)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_projectKey))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_projectKeyJoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addComponent(btn_join)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_joinChat)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String username = txt_username.getText();
        String password = txt_password.getText();

        boolean isLoggedIn = false;

        //user = new User("asd", "asd");
        for (int i = 0; i < Data.userList.size(); i++) {

            if (Data.userList.get(i).username.equals(username) && Data.userList.get(i).password.equals(password)) {
                isLoggedIn = true;
                user = Data.userList.get(i);
            }
        }

        if (isLoggedIn) {
            try {

                socket = new Socket("localhost", 5000);
                client = new Client(socket, user);
                client.Listen();
                client.sendMessage(username);

                lst_messages.setModel(client.messageList);

                btn_createProejct.setEnabled(true);
                btn_joinChat.setEnabled(true);
                btn_send.setEnabled(true);
                txt_message.setEnabled(true);
                lst_project.setEnabled(true);
                txt_projectName.setEnabled(true);

                btn_login.setEnabled(false);
                txt_username.setEnabled(false);
                txt_password.setEnabled(false);

                for (int i = 0; i < user.projectList.size(); i++) {
                    project_list.addElement(user.projectList.get(i).projectKey + " -> " + user.projectList.get(i).name);
                }

            } catch (Exception e) {
                client.Close();
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "WRONG PASSWORD OR USERNAME");
        }

    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:

        String msg = client.user.username + " : " + txt_message.getText();

        client.sendMessage(msg);

    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_joinChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinChatActionPerformed
        // TODO add your handling code here:
        String project = lst_project.getSelectedValue();

        String projectKey = project.substring(Math.max(project.length() - 4, 0));
        Project p = null;
        for (int i = 0; i < Data.projectList.size(); i++) {
            if (Data.projectList.get(i).projectKey.equals(projectKey)) {
                p = Data.projectList.get(i);
                break;
            }
        }

        ProjectFrame pFrame = new ProjectFrame(p, client, user);

        pFrame.setVisible(true);
        pFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pFrame.setLocationRelativeTo(null);


    }//GEN-LAST:event_btn_joinChatActionPerformed

    private void btn_createProejctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createProejctActionPerformed
        // TODO add your handling code here:
        String projectName = txt_projectName.getText();

        Project project = new Project(projectName);

        project.userList.add(user);
        project.userListModel.addElement(user.username);
        user.projectList.add(project);

        project_list.addElement(project.name + " -> " + project.projectKey);

        Data.projectList.add(project);
        Data.projectKeys.add(Integer.parseInt(project.projectKey));

        lbl_projectKey.setText(project.projectKey);


    }//GEN-LAST:event_btn_createProejctActionPerformed

    private void btn_joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_joinActionPerformed
        // TODO add your handling code here:
        String projectKey = txt_projectKeyJoin.getText();
        boolean isFound = false;

        Project p = null;

        for (int i = 0; i < Data.projectList.size(); i++) {
            if (projectKey.equals(Data.projectList.get(i).projectKey)) {
                p = Data.projectList.get(i);
                isFound = true;
                break;
            }
        }

        boolean isJoined = false;

        if (isFound) {

            for (int i = 0; i < p.userList.size(); i++) {
                if (p.userList.get(i) == this.user) {
                    isJoined = true;
                }
            }

            if (!isJoined) {
                p.userList.add(user);
                user.projectList.add(p);
                p.userListModel.addElement(user.username);

                project_list.addElement(p.name + " -> " + p.projectKey);
            } else {
                JOptionPane.showMessageDialog(rootPane, "YOU ALREADY JOINED THIS PROJECT");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "WRONG PROJECT KEY");
        }


    }//GEN-LAST:event_btn_joinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createProejct;
    private javax.swing.JButton btn_join;
    private javax.swing.JButton btn_joinChat;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_projectKey;
    private javax.swing.JList<String> lst_messages;
    private javax.swing.JList<String> lst_project;
    private javax.swing.JTextArea txt_message;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_projectKeyJoin;
    private javax.swing.JTextField txt_projectName;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
